# Generated by Django 3.2.5 on 2021-07-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='Image',
            field=models.ImageField(upload_to=''),
        ),
    ]
