# Generated by Django 3.2.5 on 2021-07-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='Image',
            field=models.CharField(max_length=64),
        ),
    ]
