# Generated by Django 3.2.5 on 2021-07-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='auction',
            new_name='hsgfs',
        ),
    ]
