# Generated by Django 3.2.5 on 2021-07-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='Price',
            field=models.CharField(default='$00.00', max_length=64),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='Title',
            field=models.CharField(default='Item', max_length=64),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='Image',
            field=models.ImageField(height_field=100, upload_to='', width_field=100),
        ),
    ]
