# Generated by Django 3.2.5 on 2021-07-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_auctionitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='Image',
            field=models.ImageField(default='example.jpg', height_field=100, upload_to='', width_field=100),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
