# Generated by Django 3.2.5 on 2021-07-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210723_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='Image',
            field=models.ImageField(default='example.jpg', height_field=100, upload_to='auctions', width_field=100),
        ),
    ]
