# Generated by Django 3.2.5 on 2021-07-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_auctionitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='Image',
            field=models.ImageField(default='example.jpg', upload_to=''),
        ),
    ]
