# Generated by Django 3.2.5 on 2021-07-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auctionitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='Image',
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='Price',
            field=models.CharField(default='$20.00', max_length=64),
        ),
    ]
