# Generated by Django 3.2.5 on 2021-07-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210723_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentText', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='Category',
            field=models.CharField(default='e.g. Fashion, Toys, Electronics, Home, etc.', max_length=64),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='ImageURL',
            field=models.CharField(default='Put the image link here!', max_length=1000),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='StartingBid',
            field=models.CharField(default='$22.00', max_length=8),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='description',
            field=models.CharField(default='Item Description', max_length=300),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='Price',
            field=models.CharField(default='$20.00', max_length=8),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='Title',
            field=models.CharField(default='Item Title', max_length=64),
        ),
    ]
