# Generated by Django 3.2.5 on 2021-07-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210723_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='Category',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='ImageURL',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='Price',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='StartingBid',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='Title',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
