# Generated by Django 3.2.5 on 2021-07-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20210723_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='date',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
