# Generated by Django 3.2.5 on 2021-07-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_user_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.CharField(default='', max_length=10)),
                ('Creator', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='StartingBid',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='bidList',
            field=models.ManyToManyField(blank=True, related_name='Items', to='auctions.bid'),
        ),
    ]
