# Generated by Django 3.2.5 on 2021-07-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20210727_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='closedAuctionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=64)),
                ('Description', models.CharField(default='', max_length=300)),
                ('ImageURL', models.CharField(blank=True, default='', max_length=1000)),
                ('StartingBid', models.CharField(default='', max_length=10)),
                ('Category', models.CharField(blank=True, default='', max_length=64)),
                ('date', models.CharField(blank=True, default='', max_length=64)),
                ('username', models.CharField(blank=True, default='', max_length=64)),
                ('WinnerUsername', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
    ]
