# Generated by Django 3.2.5 on 2021-07-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_closedauctionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='commentList',
            field=models.ManyToManyField(blank=True, related_name='commentItems', to='auctions.Comment'),
        ),
        migrations.AddField(
            model_name='closedauctionitem',
            name='commentList',
            field=models.ManyToManyField(blank=True, related_name='closedCommentItems', to='auctions.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='', max_length=64),
        ),
    ]
